---
# Remove unwanted libraries
- name: Remove unwanted packages
  yum: name='{{ item }}' state=absent
  with_items: '{{ yum_libraries_utilities_remove }}'

# Update system
- name: Update system packages (not kernel)
  shell: "yum update -y --exclude=kernel*"
  args:
    warn: false

# Data and apps directories
- name: DATA and APPS directories
  file: path={{ item }} state=directory mode=0775 setype=usr_t
  with_items:
  - "{{ data_dir }}"
  - "{{ apps_dir }}"

# Extra Packages for Enterprise Linux (EPEL)
- name: Extra Packages for Enterprise Linux (EPEL)
  yum: name=epel-release state=latest
- name: EPEL repository key 
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

# Libraries and utilities
- name: Libraries and utilities
  yum: name={{ item }} state=present
  with_items: "{{ yum_libraries_utilities }}"
  
# Date and time
- name: Remove old timezone file
  file: path=/etc/localtime state=absent
- name: Set America/Denver timezone
  file: src=/usr/share/zoneinfo/America/Denver dest=/etc/localtime state=link
- name: Ensure NTP is running
  service: name=ntpd state=started enabled=yes

# Disable firewall
- name: Disable FIREWALL service
  service: name=firewalld enabled=no state=stopped
  
# IPTABLES
- name: Start IPTABLES service
  service: name=iptables enabled=yes state=started

# SELinux
- name: SELinux should be enforcing
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=enforcing
- name: Enable SELinux
  command: setenforce 1

# Fix the export in global environment
- name: Fix environment export paths
  lineinfile:
    dest: /etc/bashrc
    regexp: '^export PATH=\/'
    insertafter: '# vim:ts=4:sw=4'
    line: 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin'
