---
# All servers get some common stuff
- hosts: all
  become: yes
  gather_facts: yes
  roles:
  - role: common
    tags: common

# Build servers
- hosts: build_servers
  become: yes
  gather_facts: yes
  roles:
  - role: java
    tags: java
  - role: maven
    tags: maven