---
# GIT version
- name: Query for Git version
  shell: git --version 2>&1 | grep -E "git version [0-9]+\.[0-9]+\.[0-9]+" | awk '{print $3}'
  register: installed_git_version
- name: Set Git version
  set_fact:
    GIT_VERSION: "{{ installed_git_version.stdout }}"
    GIT_NOT_INSTALLED: "{{ git_version not in installed_git_version.stdout }}"
- name: Installed Git version
  debug: msg="Installed Git version = {{ GIT_VERSION }}"
